# Generated by Django 4.2.4 on 2023-08-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articletags_tag_articletags_teg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletags',
            old_name='teg',
            new_name='tag',
        ),
    ]
